=== ChristopherRabotin/gofetch/docs/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/config" xmlns:tns="http://www.example.org/config" elementFormDefault="qualified">

    <element name="config">
    	<complexType>
    		<sequence>
    			<element name="index" type="tns:indexType" minOccurs="0"
    				maxOccurs="unbounded">
    				<annotation>
    					<documentation>
    						List of indexes. The canonical index is
    						always enabled.
    					</documentation>
    				</annotation>
    			</element>
    			<element name="throttle" type="tns:throttleType" minOccurs="0" maxOccurs="unbounded"></element>
    			<element name="urls" type="tns:urlsType" minOccurs="1"
    				maxOccurs="1">
    				<annotation>
    					<documentation>
    						List of URL elements.
    					</documentation>
    				</annotation>
    			</element>
    		</sequence>
    	</complexType>
    </element>

    <complexType name="urlType">
    	<sequence>
    		<element name="link" type="string" minOccurs="1" maxOccurs="1">
    			<annotation>
    				<documentation>Link to scrape. It is an element because some links may be very long (as per XML recommendation).</documentation>
    			</annotation></element>
    		<element name="parser" type="tns:parserType" minOccurs="1" maxOccurs="1">
    			<annotation>
    				<documentation>Parser information.</documentation>
    			</annotation></element>
    	</sequence>
    </complexType>

    <complexType name="urlsType">
    	<sequence>
    		<element name="url" type="tns:urlType" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="indexType">
    	<attribute name="name" type="string" use="required">
    		<annotation>
    			<documentation>Name of the index, as understood by the fetcher.</documentation>
    		</annotation></attribute>
    	<attribute name="enabled" type="boolean" use="required">
    		<annotation>
    			<documentation>Enabled status.</documentation>
    		</annotation></attribute>
    </complexType>

    <complexType name="parserType">
        <annotation>
        	<documentation>Stores parser metadata.</documentation>
        </annotation>
        <sequence>
	        <any processContents="skip" minOccurs="0"/>
	    </sequence>
        <attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="throttleType">
    	<attribute name="host" type="string" use="required">
    		<annotation>
    			<documentation>Hostname and port number, if applicable. Must *exactly* match the &gt;link&lt; string to work.</documentation>
    		</annotation></attribute>
    	<attribute name="delay" type="float" use="required">
    		<annotation>
    			<documentation>Delay as a float, whose unit is in unit.</documentation>
    		</annotation></attribute>
    	<attribute name="unit" type="string" use="required">
    		<annotation>
    			<documentation>Unit of the delay, defaults to seconds. Accepted units as defined in Go: http://golang.org/pkg/time/#ParseDuration .</documentation>
    		</annotation></attribute>
    </complexType>
</schema>

=== ChristopherRabotin/gofetch/docs/examples/config.example.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://fetcher.sparrho.com/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://fetcher.sparrho.com/config ../config.xsd ">
	<index enabled="true" name="checksum" />
	<throttle host="example.com" delay="2.5" unit="s" />
	<urls>
		<url>
			<link>http://informahealthcare.com/action/showFeed?jc=smr&amp;type=etoc&amp;feed=rss</link>
			<parser name="rss">
				<feed id="8850" name="Somatosensory &amp; Motor Research" />
			</parser>
		</url>
		<url>
			<link>http://export.arxiv.org/oai2?verb=ListRecords&amp;metadataPrefix=arXiv&amp;from=2015-04-13&amp;until=2015-04-14</link>
			<parser name="arxiv_OAI">
				<config metadataPrefix="arxiv" followResumptionToken="true"
					base_url="http://export.arxiv.org/oai2" />
			</parser>
		</url>
		<url>
			<link>http://onlinelibrary.wiley.com/journal/10.1002/(ISSN)1616-3028</link>
			<parser name="wiley">
				<config name="Advanced Functional Materials" link_filter="/issuetoc" />
			</parser>
		</url>
	</urls>
</config>

=== ChristopherRabotin/gofetch/test_config_nominal.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://fetcher.sparrho.com/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://fetcher.sparrho.com/config docs/config.xsd ">
	<throttle delay="10" unit="ms" host="example.s3.amazonaws.com" />
	<throttle delay="10" unit="carrots" host="example.com" />
	<urls>
		<url>
			<link>http://example.s3.amazonaws.com/gofetch/test_data/feeds/apa-journals-pas.xml</link>
			<parser name="RawArticle">
				<feed id="11335" name="Psychological Assessment" />
			</parser>
		</url>
		<url>
			<link>http://example.s3.amazonaws.com/gofetch/test_data/feeds/dydan1.xml</link>
			<parser name="RawArticle">
				<feed id="5592" name="dydan1" />
			</parser>
		</url>
		<url>
			<!-- This is duplicated to test indexing. -->
			<link>http://example.s3.amazonaws.com/gofetch/test_data/feeds/apa-journals-pas.xml</link>
			<parser name="RawArticle">
				<feed id="11335" name="Psychological Assessment" />
			</parser>
		</url>
		<url>
			<link>http:/some.invalid.com/link</link>
			<parser name="RawArticle">
				<feed id="11335" name="Psychological Assessment" />
			</parser>
		</url>
	</urls>
</config>

=== ChristopherRabotin/gofetch/config.demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://fetcher.sparrho.com/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://fetcher.sparrho.com/config docs/config.xsd ">
	<throttle delay="20" unit="s" host="feeds.feedburner.com" />
	<urls>
		<url>
			<link>http://feeds.feedburner.com/acs/joceah</link>
			<parser name="rss">
				<feed id="8850" name="joceah" />
			</parser>
		</url>
		<url>
			<link>http://feeds.feedburner.com/apa-journals-pas?format=xml</link>
			<parser name="rss">
				<feed id="11335" name="Psychological Assessment" />
			</parser>
		</url>
		<url>
			<link>http://feeds.feedburner.com/dydan1</link>
			<parser name="rss">
				<feed id="5592" name="dydan1" />
			</parser>
		</url>
	</urls>
</config>
